import type { SiteCopy } from '../types';
export default {
  meta: { description: 'Organizza le spese, pianifica il mese e fai spazio al risparmio. Scopri Vetra, l’app di finanza personale senza pubblicità, con sincronizzazione facoltativa.' },
  nav: { features: 'Scopri', demo: 'Prova Vetra', faq: 'Domande', download: 'Vedi su Google Play', language: 'Lingua', theme: 'Cambia tema', skip: 'Vai al contenuto' },
  hero: { eyebrow: 'PIÙ CHIAREZZA. PIÙ TRANQUILLITÀ.', title: 'Fai spazio a ciò che conta.', text: 'Le tue spese, i tuoi progetti e quello che viene dopo. Riunisci le tue finanze in un posto che resta semplice.', note: 'Attualmente disponibile tramite test chiusi su Google Play.', chips: ['Senza pubblicità', 'Al tuo ritmo', 'Scegli tu'] },
  planning: { eyebrow: 'UN PIANO CHE SI ADATTA A TE', title: 'Il tuo mese. Non solo un calendario.', text: 'Da uno stipendio al successivo, dai il giusto spazio a spese quotidiane, bollette e risparmi. Sai cosa hai accantonato e cosa è ancora disponibile.', items: ['Conti da pagare', 'Ogni giorno', 'Risparmi'] },
  clarity: { eyebrow: 'IL QUADRO COMPLETO, SENZA RUMORE', title: 'Tutto diventa più chiaro.', text: 'Vedi i tuoi conti insieme, trova un movimento in pochi secondi e capisci dove va il denaro. I dettagli utili, quando servono.', items: ['Conti insieme', 'Movimenti chiari', 'Analisi utile'] },
  demo: { eyebrow: 'MENO LETTURA. PIÙ SCOPERTA.', title: 'Un piccolo assaggio di Vetra.', text: 'Aggiungi una spesa. Metti da parte qualcosa. Guarda come tornano i conti. Questo esempio interattivo usa dati fittizi, non i tuoi conti reali.', tabs: ['Riepilogo', 'Movimenti', 'Piano'], fields: ['Importo', 'Descrizione', 'Categoria', 'Conto', 'Accantonare', 'Salva', 'Ricomincia', 'Chiudi'], labels: ['Saldo totale', 'Speso', 'Accantonato', 'Disponibile'], accounts: ['Conto corrente', 'Risparmi', 'Portafoglio'], categories: ['Alimentari', 'Trasporti'], actions: ['Aggiungi spesa', 'Accantona per risparmiare', 'Prova la demo'], goal: 'Fondo di emergenza', warning: 'Demo · dati fittizi · EUR', loading: 'Apertura della demo…', error: 'Controlla i campi e riprova.', success: 'Salvato in questa demo.' },
  details: { eyebrow: 'PICCOLI DETTAGLI. UNA VERA DIFFERENZA.', title: 'Per la tua vita reale.', text: 'Il denaro non è solo un totale mensile. Vetra fa spazio anche ai dettagli.', items: [{ title: 'Un posto per ogni obiettivo', text: 'Separa il denaro nei salvadanai e segui i tuoi obiettivi di risparmio.' }, { title: 'Un conto condiviso', text: 'Consulta insieme agli altri il saldo e i movimenti di un conto condiviso.' }, { title: 'Nulla viene dimenticato', text: 'Tieni traccia di ciò che ti devono e registra i rimborsi quando arrivano.' }] },
  trust: { eyebrow: 'IL TUO DENARO. LE TUE DECISIONI.', title: 'Più tranquillità per le tue finanze.', text: 'Nessuna pubblicità tra i piedi. Nessun collegamento bancario obbligatorio. Decidi tu se utilizzare la sincronizzazione cloud.', items: [{ title: 'Funziona offline', text: 'Gestisci le finanze offline dopo la configurazione iniziale. Accesso e servizi cloud richiedono Internet.' }, { title: 'Sincronizza quando vuoi', text: 'Attiva la sincronizzazione per avere i dati del tuo account su più dispositivi.' }, { title: 'Conserva un backup', text: 'Salva un backup Vetra per ripristinare i dati o esporta un PDF per consultarli.' }] },
  faq: { title: 'Forse ti stai chiedendo…', items: [{ title: 'Devo collegare la mia banca?', text: 'No. Registri personalmente i movimenti. Vetra non è una banca e non effettua pagamenti al posto tuo.' }, { title: 'Quali valute posso scegliere?', text: 'EUR, USD, GBP, CNY, CHF, AUD, CAD e BRL. La valuta scelta durante la configurazione si applica alle tue finanze. Cambiarla in seguito non è ancora disponibile.' }, { title: 'La sincronizzazione è obbligatoria?', text: 'No. Puoi conservare i dati sul dispositivo. In questo caso, salva regolarmente copie di sicurezza.' }, { title: 'Posso usarla senza Internet?', text: 'Sì, dopo la configurazione iniziale. Autenticazione e servizi cloud richiedono una connessione.' }, { title: 'Posso già provarla?', text: 'Vetra è in fase di test chiusi su Google Play. Apri la scheda per verificare se puoi accedere.' }] },
  footer: { title: 'Un po’ più di chiarezza, ogni giorno.', text: 'Affronta il prossimo mese con un po’ più di leggerezza.', privacy: 'Privacy', contact: 'Contattaci', deletion: 'Richiedi eliminazione account', rights: 'Creata con cura. Senza pubblicità.', images: 'Esplora l’interfaccia reale' },
} satisfies SiteCopy;
